// components/Comment.tsx
import tw, { styled } from 'twin.macro';
import { Comment as ApiComment, VideoInfo } from '~/lib/video';
import PinIcon from '~icons/ri/pushpin-line.jsx';
import ChannelName from './ChannelName';
import LikeIcon from '~icons/ri/thumb-up-line.jsx';
import ChevronUpIcon from '~icons/ri/arrow-up-s-line.jsx';
import ChevronDownIcon from '~icons/ri/arrow-down-s-line.jsx';
import { formatNumber } from '~/lib/util';
import { useState } from 'react';
import { useComments } from '~/lib/hooks';
import Spinner from '~/components/Spinner';
import ArrowRightIcon from '~icons/ri/arrow-right-line.jsx';

const Wrapper = tw.div`flex gap-4`;
const ProfilePicture = tw.img`rounded-full w-10 h-10`;
const ContentWrapper = tw.div`flex-1`;
const Supertitle = tw.p`text-sm text-gray-700`;
const Pin = styled(PinIcon, tw`inline-block align-middle mr-1 mb-1`);
const Title = tw.h1`font-semibold mb-0.5`;
const Content = tw.p`whitespace-pre-line`;
const Timestamp = tw.span`font-normal text-sm text-gray-700 ml-2`;
const LikeBar = tw.div`mt-2 text-sm text-gray-700`;
const Like = styled(LikeIcon, tw`inline-block align-middle mr-2 mb-0.5`);
const RepliesButton = tw.button`mt-2 text-blue-700 font-semibold`;
const ShowReplies = styled(ChevronDownIcon, tw`inline-block align-middle mr-1 mb-0.5`);
const HideReplies = styled(ChevronUpIcon, tw`inline-block align-middle mr-1 mb-0.5`);
const RepliesWrapper = tw.div`flex flex-col items-start gap-4 mt-4`;
const ArrowRight = styled(ArrowRightIcon, tw`inline-block align-middle mr-1 mb-0.5`);
const Loader = tw.div`w-full flex justify-center`;

const Comment: React.FC<{ video: VideoInfo; comment: ApiComment }> = ({ video, comment }) => {
	const author = comment.author;

	const [expanded, setExpanded] = useState(false);
	const { comments, loadMore, fetching, done } = useComments(
		video.metadata.id,
		comment.replyToken
	);

	function toggleExpanded() {
		fetchMore();
		setExpanded((e) => !e);
	}

	function fetchMore() {
		if (!fetching && !done) {
			loadMore();
		}
	}

	return (
		<Wrapper>
			<ProfilePicture loading="lazy" src={author.avatar} alt={author.name} />
			<ContentWrapper>
				{comment.pinned && (
					<Supertitle>
						<Pin />
						Pinned
					</Supertitle>
				)}
				<Title>
					<ChannelName verified={author.verified}>{author.name}</ChannelName>
					<Timestamp>
						{comment.time} {comment.edited ? '(edited)' : ''}
					</Timestamp>
				</Title>
				<Content>{comment.text}</Content>
				<LikeBar>
					<Like />
					{formatNumber(comment.likes, true)}
				</LikeBar>
				{comment.replies !== 0 && (
					<RepliesButton onClick={toggleExpanded}>
						{expanded ? <HideReplies /> : <ShowReplies />}
						{expanded ? 'hide' : 'show'} {comment.replies}
						{comment.replies === 1 ? ' reply' : ' replies'}
						{comment.ownerReplied
							? ` from ${video.metadata.author.name} and others`
							: ''}
					</RepliesButton>
				)}
				{expanded && (
					<RepliesWrapper>
						{comments.map((comment) => (
							<Comment key={comment.id} video={video} comment={comment} />
						))}
						{fetching && (
							<Loader>
								<Spinner />
							</Loader>
						)}
						{!fetching && !done && (
							<RepliesButton onClick={fetchMore}>
								<ArrowRight /> fetch more replies
							</RepliesButton>
						)}
					</RepliesWrapper>
				)}
			</ContentWrapper>
		</Wrapper>
	);
};

export default Comment;

// components/watch/Comment.vue
<script setup lang="ts">
import { PropType } from 'vue';
import { Comment, Comments, formatNumber, Video } from '~/lib/api';

import Reply from './Comment.vue';

const props = defineProps({
	comment: { type: Object as PropType<Comment>, required: true },
	video: { type: Object as PropType<Video>, required: true },
});

const expanded = ref(false);
const fetching = ref(false);
const replies = ref<Comments>();

async function fetchReplies() {
	if (fetching.value) {
		return;
	}

	fetching.value = true;
	if (!replies.value) {
		replies.value = await $fetch(
			`/api/video/${props.video.metadata.id}/comments?replies=${props.comment.replyToken}`
		);
	} else {
		const res = await $fetch<Comments>(
			`/api/video/${props.video.metadata.id}/comments?replies=${replies.value.continuation}`
		);

		replies.value.comments = replies.value.comments.concat(res.comments);
		replies.value.continuation = res.continuation;
	}
	fetching.value = false;
}

function toggleExpanded() {
	expanded.value = !expanded.value;

	if (expanded.value && !replies.value) {
		fetchReplies();
	}
}
</script>

<template>
	<div display-flex flex="gap-4">
		<img
			v-lazy="props.comment.author.avatar"
			:alt="`${props.comment.author.name}'s avatar`"
			w-10
			h-10
			bg="gray-200"
			border="rounded-full"
		/>
		<div>
			<p v-if="props.comment.pinned" text="sm gray-700">
				<i inline-block m="r-0.5 b-1" align="middle" i-ri-pushpin-line />
				Pinned
			</p>
			<h1 m="b-0.5" font="semibold">
				{{ props.comment.author.name }}
				<i
					v-if="props.comment.author.verified"
					inline-block
					m="b-0.5"
					align="middle"
					i-ri-check-line
				/>
				<span ml-2 text="sm gray-700" font="normal">
					{{ props.comment.time }}
					<template v-if="props.comment.edited">(edited)</template>
				</span>
			</h1>
			<p whitespace="pre-line">{{ props.comment.text }}</p>
			<div mt-2 text="sm gray-700">
				<i inline-block m="r-0.5 b-1" align="middle" i-ri-thumb-up-line />
				{{ formatNumber(props.comment.likes) }}
			</div>
			<div v-if="props.comment.replies != 0" mt-2>
				<button font="semibold" text="blue-700" @click="toggleExpanded">
					<i
						v-if="expanded"
						inline-block
						m="r-1 b-0.5"
						align="middle"
						i-ri-arrow-up-s-line
					/>
					<i v-else inline-block m="r-1 b-0.5" align="middle" i-ri-arrow-down-s-line />
					{{ expanded ? 'hide' : 'show' }} {{ props.comment.replies }} replies
					<template v-if="props.comment.ownerReplied">
						from {{ props.video.metadata.author.name }} and others
					</template>
				</button>

				<div v-if="expanded" mt-4>
					<template v-if="replies">
						<Reply
							v-for="reply in replies.comments"
							:key="reply.id"
							:comment="reply"
							:video="props.video"
							mb-4
						/>
					</template>
					<div v-if="!replies || fetching" display="flex" justify="center">
						<Spinner></Spinner>
					</div>
					<button
						v-if="replies && replies.continuation && !fetching"
						font="semibold"
						text="blue-700"
						@click="fetchReplies"
					>
						<i inline-block m="r-1 b-0.5" align="middle" i-ri-arrow-right-line />
						fetch more replies
					</button>
				</div>
			</div>
		</div>
	</div>
</template>
