// components/watch/CommentSection.vue
<script setup lang="ts">
import { Comments, Video } from '~/lib/api';
import { PropType } from 'vue';
import Comment from '~/components/watch/Comment.vue';

const props = defineProps({
	video: { type: Object as PropType<Video>, required: true },
});

const comments = ref<Comments>();
const fetching = ref(false);

async function fetch() {
	if (fetching.value) {
		return;
	}

	fetching.value = true;

	if (!comments.value) {
		comments.value = await $fetch(`/api/video/${props.video.metadata.id}/comments`);
	} else {
		const res = await $fetch<Comments>(
			`/api/video/${props.video.metadata.id}/comments?continuation=${comments.value.continuation}`
		);

		comments.value.comments = comments.value.comments.concat(res.comments);
		comments.value.continuation = res.continuation;
	}

	fetching.value = false;
}
</script>

<template>
	<div>
		<Comment
			v-for="comment in comments?.comments || []"
			:key="comment.id"
			:comment="comment"
			:video="props.video"
			mb-6
		/>
		<p v-if="comments && comments.comments.length == 0" text="center">No comments.</p>
	</div>
	<OnScreen
		v-if="!comments || comments.continuation"
		display="flex"
		justify="center"
		@on-screen="fetch"
	>
		<Spinner mt-8 />
	</OnScreen>
</template>

// components/CommentSection.tsx
import { useEffect, useRef } from 'react';
import tw from 'twin.macro';
import Spinner from '~/components/Spinner';
import Comment from '~/components/Comment';
import { useComments, useOnScreen } from '~/lib/hooks';
import { VideoInfo } from '~/lib/video';
import { formatNumber } from '~/lib/util';

const Notice = tw.p`text-center mt-4`;
const Wrapper = tw.div`flex flex-col gap-6`;
const Loader = tw.div`flex justify-center mt-8`;

const CommentSection: React.FC<{ video: VideoInfo }> = ({ video }) => {
	const spinner = useRef<HTMLElement>(null);
	const isVisible = useOnScreen(spinner);

	const { total, comments, loadMore, fetching, done } = useComments(video.metadata.id);

	useEffect(() => {
		if (isVisible && !fetching) {
			loadMore();
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [isVisible]);

	return (
		<Wrapper>
			{total && comments.length > 0 && <p>{formatNumber(total)} comments</p>}
			{done && comments.length == 0 && <Notice>No comments.</Notice>}
			{comments.map((comment) => (
				<Comment key={comment.id} video={video} comment={comment} />
			))}
			{!done && (
				<Loader>
					<Spinner ref={spinner} />
				</Loader>
			)}
		</Wrapper>
	);
};

export default CommentSection;
