// components/watch/RelatedVideo.vue
<script setup lang="ts">
import { PropType } from 'vue';
import { formatDistanceToNow } from 'date-fns';
import { VideoMetadata } from '~/lib/api';

const props = defineProps({
	video: { type: Object as PropType<VideoMetadata>, required: true },
});
</script>

<template>
	<NuxtLink :to="`/watch?v=${props.video.id}`" display="flex" flex="gap-2" h="auto" mb-4>
		<img
			v-lazy="props.video.thumbnail"
			:alt="props.video.title"
			flex="none basis-[168px]"
			h="[94px]"
			bg="gray-200"
			object-cover
		/>
		<div>
			<h1 font="semibold" text="sm" line-clamp-2>
				{{ props.video.title }}
			</h1>
			<p mt-1 text="sm gray-700">
				{{ props.video.author.name }}
				<i
					v-if="props.video.author.verified"
					i-ri-check-line
					align="middle"
					m="b-0.5"
					inline-block
				/>
			</p>
			<p text="sm gray-700">
				{{ props.video.views.toLocaleString() }} views -
				{{ formatDistanceToNow(new Date(props.video.publishDate), { addSuffix: true }) }}
			</p>
		</div>
	</NuxtLink>
</template>

// components/RelatedVideo.tsx
import Link from 'next/link';
import tw, { styled } from 'twin.macro';
import { formatDuration, formatNumber } from '~/lib/util';
import { VideoMetadata } from '~/lib/video';
import ChannelName from './ChannelName';
import { formatDistanceToNowStrict } from 'date-fns';

const Wrapper = tw.a`flex gap-2`;
const ThumbnailWrapper = styled.div({ ...tw`h-[94px] bg-gray-200 relative`, flex: '0 0 168px' });
const Thumbnail = tw.img`w-full h-full object-cover`;
const Duration = tw.span`absolute bottom-2 right-2 font-semibold text-xs text-white bg-black bg-opacity-75 px-1 pb-0.5`;
const Title = tw.h1`text-sm font-semibold line-clamp-2 mb-1`;
const Subtitle = tw.h2`text-sm text-gray-700`;

const RelatedVideo: React.FC<{ meta: VideoMetadata }> = ({ meta }) => {
	const author = meta.author;

	return (
		<Link href={`/watch?v=${meta.id}`} passHref>
			<Wrapper>
				<ThumbnailWrapper>
					<Thumbnail loading="lazy" src={meta.thumbnail} alt={meta.title} />
					<Duration>{formatDuration(meta.lengthSeconds)}</Duration>
				</ThumbnailWrapper>
				<div>
					<Title>{meta.title}</Title>
					<Subtitle>
						<ChannelName verified={author.verified}>{author.name}</ChannelName>
					</Subtitle>
					<Subtitle>
						{formatNumber(meta.views)}
						{' views - '}
						{formatDistanceToNowStrict(new Date(meta.publishDate), { addSuffix: true })}
					</Subtitle>
				</div>
			</Wrapper>
		</Link>
	);
};

export default RelatedVideo;
